name: ClickMe
main: net.digiex.clickme
version: 1.0
author: xzKinGzxBuRnzx
permissions:
  clickme.player:
    description: Allows sign based commands as player.
    default: true
  clickme.console:
    description: Allows sign based commands as console.
    default: op